export const PhrasesCollection = [
	"Hi!",
	"Hello there!",
	"How are you today?",
	"Nice weather, isn't it?",
	"What can I do for you?",
	"Is there anything I can assist you with?",
	"I hope you're having a great day!",
	"Just passing by to say hello!",
	"Enjoying the view?",
	"I'm here to make your life easier!",
	"Let me know if you need anything!",
	"I'm at your service!",
	"We need to add more beacons!",
	"Welcome to our unknown planet!",
	"Exploring the mysteries of this planet!",
	"Isn't this planet fascinating?",
	"Discovering new life forms!",
	"Adventures await on this unknown planet!",
	"Uncovering the secrets of this alien world!",
];