export const PhrasesCollection = [
	"Hello there!",
	"How are you today?",
	"Nice weather, isn't it?",
	"What can I do for you?",
	"Is there anything I can assist you with?",
	"I hope you're having a great day!",
	"Just passing by to say hello!",
	"Enjoying the view?",
	"I'm here to make your life easier!",
	"Let me know if you need anything!",
	"I'm at your service!",
	"We need to add more beacons!",
	"Welcome to our unknown planet!",
	"Exploring the mysteries of this planet!",
	"Isn't this planet fascinating?",
	"Discovering new life forms!",
	"Adventures await on this unknown planet!",
	"Uncovering the secrets of this alien world!",
	"Detecting unusual energy signatures nearby.",
	"Discovered a rare resource deposit!",
	"Caution: Hazardous terrain ahead.",
	"Scanning for hidden artifacts...",
	"Analyzing unknown flora and fauna.",
	"Decrypting ancient alien transmissions.",
	"Mapping uncharted territories.",
	"Investigating mysterious structures.",
	"Tracking valuable resource veins.",
	"Warning: Seismic activity detected.",
	"Uncovering the planet's dark secrets.",
	"Calculating optimal extraction points.",
	"Discovering remnants of an ancient civilization.",
	"Navigating through treacherous canyons.",
	"Analyzing atmospheric composition.",
	"Detecting signs of intelligent life.",
	"Exploring vast underground caverns.",
	"Tracking migration patterns of alien species.",
	"Investigating peculiar gravitational anomalies.",
	"Uncovering the origins of this world.",
	"Scanning for potential settlement sites.",
	"Analyzing the planet's unique ecosystem.",
	"Discovering hidden oases in the desert.",
	"Investigating the ruins of an alien city.",
	"Mapping the constellations in the alien sky.",
	"Tracking the source of mysterious energy pulses.",
	"Analyzing the planet's geological history.",
	"Discovering clues to the planet's past.",
	"Uncovering the secrets of the ancient ruins.",
	"Investigating the cause of strange weather patterns.",
	"Scanning for rare and valuable minerals.",
	"Analyzing the planet's magnetic field.",
	"Discovering hidden caves filled with bioluminescent life.",
	"Tracking the signs of an intelligent alien species.",
	"Investigating the remains of an alien spacecraft.",
	"Uncovering the truth behind the planet's mysteries.",
	"Analyzing the planet's unique gravitational properties.",
	"Discovering ancient alien technology.",
	"Scanning for signs of potential danger.",
	"Investigating the planet's unusual day-night cycle.",
	"Uncovering the secrets hidden in the planet's core.",
	"Analyzing the planet's atmospheric storms.",
	"Discovering new frontiers on this alien world.",
];